name: 申请译者
description: 表单
title: "申请译者"
labels: ["申请译者"]
assignees:
  - devgogo
body:
  - type: input
    id: org
    attributes:
      label: 所在学校/公司
      placeholder: 可选
    validations:
      required: false
  - type: input
    id: domain
    attributes:
      label: 技术方向
      placeholder: 翻译内容领域
    validations:
      required: true
  - type: input
    id: level
    attributes:
      label: 英语能力
    validations:
      required: true
  - type: dropdown
    id: undergo
    attributes:
      label: 翻译经验
      options:
        - 有
        - 无
  - type: input
    id: homepage
    attributes:
      label: 个人主页/播客
  - type: input
    id: bio
    attributes:
      label: 个人介绍
      placeholder: 可选
